# Generated by Django 2.0.6 on 2018-06-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_index=True, help_text='todo entry text', max_length=1024, verbose_name='Content')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text="When it's created", verbose_name='Create time')),
            ],
            options={
                'verbose_name': 'List item',
                'verbose_name_plural': 'List items',
            },
        ),
    ]
