# Generated by Django 2.0.6 on 2018-07-02 06:22

from django.db import migrations


def create_list(apps, schema_editor):
    List = apps.get_model("todo", "List")
    Item = apps.get_model("todo", "Item")
    initial_list = List.objects.create()
    initial_list.entries.set(Item.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180702_0621'),
    ]

    operations = [
        migrations.RunPython(code=create_list),
    ]
